version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    volumes:
      - sab_postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "9642:8080"

  backend:
    build: ./backend
    restart: always
    env_file: .env
    depends_on:
      - postgres

  nginx:
    image: nginx:1.24.0-alpine
    restart: always
    volumes:
      - ./nginx/conf/backend.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - postgres
      - backend

volumes:
  sab_postgres_data:
